<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Images\" />
    <Folder Include="Converters\" />
    <Folder Include="Interface\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invento.DataAccess\Invento.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SearchText">
      <HintPath>..\..\..\..\..\Easing tools\WPFControls\SearchText\SearchTextControl\SearchText\bin\Debug\net5.0-windows\SearchText.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
