// <auto-generated />
using System;
using Invento.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invento.DataAccess.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250305141642_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invento.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Books"
                        });
                });

            modelBuilder.Entity("Invento.Model.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("InventoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            InventoryName = "Store A"
                        });
                });

            modelBuilder.Entity("Invento.Model.InventoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 885, DateTimeKind.Local).AddTicks(3162),
                            Quantity = 10
                        },
                        new
                        {
                            ItemId = 2,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6408),
                            Quantity = 20
                        },
                        new
                        {
                            ItemId = 3,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6481),
                            Quantity = 10
                        },
                        new
                        {
                            ItemId = 4,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6488),
                            Quantity = 50
                        },
                        new
                        {
                            ItemId = 5,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6493),
                            Quantity = 20
                        },
                        new
                        {
                            ItemId = 6,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6497),
                            Quantity = 30
                        },
                        new
                        {
                            ItemId = 7,
                            InventoryId = 1,
                            LastUpdate = new DateTime(2025, 3, 5, 16, 16, 36, 956, DateTimeKind.Local).AddTicks(6502),
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("Invento.Model.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1,
                            ItemName = "ASUS Vivobook"
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 1,
                            ItemName = "Huawei MatePad"
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 2,
                            ItemName = "Fit Polo Shirt"
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 2,
                            ItemName = "The North Face Jacket"
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 3,
                            ItemName = "The Art of Computer Programming"
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 3,
                            ItemName = "Programming C# 12"
                        },
                        new
                        {
                            ItemId = 7,
                            CategoryId = 1,
                            ItemName = "Samsung Galaxy S25 Ultra Dual SIM"
                        });
                });

            modelBuilder.Entity("Invento.Model.InventoryItem", b =>
                {
                    b.HasOne("Invento.Model.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invento.Model.Item", "Item")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Invento.Model.Item", b =>
                {
                    b.HasOne("Invento.Model.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Invento.Model.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Invento.Model.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Invento.Model.Item", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
